window.library = [            
            { p: "ਹਾਂ", pr: "Haan", en: "Yes", hi: "हाँ", te: "అవును", em: "✅" },
            { p: "ਨਹੀਂ", pr: "Nahi", en: "No", hi: "नहीं", te: "కాదు", em: "❌" },
            { p: "ਕਿਰਪਾ ਕਰਕੇ", pr: "Kirpa karke", en: "Please", hi: "कृपया", te: "దయచేసి", em: "🙏" },
            { p: "ਮਾਫ਼ ਕਰਨਾ", pr: "Maaf karna", en: "Excuse me / Sorry", hi: "माफ़ करना", te: "క్షమించండి", em: "🙇" },
            { p: "ਜੀ ਆਇਆਂ ਨੂੰ", pr: "Ji aayan nu", en: "Welcome", hi: "स्वागत है", te: "స్వాగతం", em: "🙌" },
            { p: "ਅਲਵਿਦਾ", pr: "Alvida", en: "Goodbye", hi: "अलविदा", te: "సెలవు", em: "👋" },
            { p: "ਠੀਕ ਹੈ", pr: "Theek hai", en: "Okay / All right", hi: "ठीक है", te: "సరే", em: "👌" },
            { p: "ਮਾਂ", pr: "Maan", en: "Mother", hi: "माँ", te: "అమ్మ", em: "👩" },
            { p: "ਪਿਤਾ", pr: "Pita", en: "Father", hi: "पिता", te: "నాన్న", em: "👨" },
            { p: "ਭਰਾ", pr: "Bharaa", en: "Brother", hi: "भाई", te: "సహోదరుడు", em: "👦" },
            { p: "ਭੈਣ", pr: "Bhain", en: "Sister", hi: "बहन", te: "సోదరి", em: "👧" },
            { p: "ਦੋਸਤ", pr: "Dost", en: "Friend", hi: "दोस्त", te: "స్నేహితుడు", em: "🤝" },
            { p: "ਘਰ", pr: "Ghar", en: "House / Home", hi: "घर", te: "ఇల్లు", em: "🏠" },
            { p: "ਕਿਤਾਬ", pr: "Kitaab", en: "Book", hi: "किताब", te: "పుస్తకం", em: "📖" },
            { p: "ਗੱਡੀ", pr: "Gaddi", en: "Car / Vehicle", hi: "गाड़ी", te: "కారు", em: "🚗" },
            { p: "ਪੈਸੇ", pr: "Paise", en: "Money", hi: "पैसे", te: "డబ్బులు", em: "💵" },
            { p: "ਫੋਨ", pr: "Phon", en: "Phone", hi: "फ़ोन", te: "ఫోన్", em: "📱" },
            { p: "ਸਕੂਲ", pr: "Skool", en: "School", hi: "स्कूल", te: "బడి", em: "🏫" },
            { p: "ਦੁੱਧ", pr: "Dudh", en: "Milk", hi: "दूध", te: "పాలు", em: "🥛" },
            { p: "ਚਾਹ", pr: "Chaah", en: "Tea", hi: "चाय", te: "టీ", em: "☕" },
            { p: "ਫਲ", pr: "Phal", en: "Fruit", hi: "फल", te: "పండు", em: "🍌" },
            { p: "ਸਬਜ਼ੀ", pr: "Sabzee", en: "Vegetable", hi: "सब्जी", te: "కూరగాయ", em: "🥦" },
            { p: "ਅੱਜ", pr: "Ajj", en: "Today", hi: "आज", te: "ఈరోజు", em: "📅" },
            { p: "ਕੱਲ੍ਹ", pr: "Kalh", en: "Tomorrow / Yesterday", hi: "कल", te: "రేపు / నిన్న", em: "⏳" },
            { p: "ਇੱਕ", pr: "Ikk", en: "One", hi: "एक", te: "ఒకటి", em: "1️⃣" },
            { p: "ਦੋ", pr: "Do", en: "Two", hi: "दो", te: "రెండు", em: "2️⃣" },
            { p: "ਤਿੰਨ", pr: "Tinn", en: "Three", hi: "तीन", te: "మూడు", em: "3️⃣" },
            { p: "ਲਾਲ", pr: "Laal", en: "Red", hi: "लाल", te: "ఎరుపు", em: "🔴" },
            { p: "ਨੀਲਾ", pr: "Neela", en: "Blue", hi: "नीला", te: "నీలం", em: "🔵" },
            { p: "ਹਰਾ", pr: "Haraa", en: "Green", hi: "हरा", te: "ఆకుపచ్చ", em: "🟢" },
            { p: "ਪੀਲਾ", pr: "Peela", en: "Yellow", hi: "पीला", te: "పసుపు", em: "🟡" },
            { p: "ਕਾਲਾ", pr: "Kaala", en: "Black", hi: "काला", te: "నలుపు", em: "⚫" },
            { p: "ਚਿੱਟਾ", pr: "Chitta", en: "White", hi: "सफेद", te: "తెలుపు", em: "⚪" },
            { p: "ਗੁਲਾਬੀ", pr: "Gulaabi", en: "Pink", hi: "गुलाबी", te: "గులాబీ", em: "🌸" },
            { p: "ਕੁੱਤਾ", pr: "Kutta", en: "Dog", hi: "कुत्ता", te: "కుక్క", em: "🐶" },
            { p: "ਬਿੱਲੀ", pr: "Billi", en: "Cat", hi: "बिल्ली", te: "పిల్లి", em: "🐱" },
            { p: "ਗਾਂ", pr: "Gaan", en: "Cow", hi: "गाय", te: "ఆవు", em: "🐄" },
            { p: "ਘੋੜਾ", pr: "Ghora", en: "Horse", hi: "घोड़ा", te: "గుర్రం", em: "🐴" },
            { p: "ਸ਼ੇਰ", pr: "Sher", en: "Lion", hi: "शेर", te: "సింహం", em: "🦁" },
            { p: "ਪੰਛੀ", pr: "Panchhi", en: "Bird", hi: "पक्षी", te: "పక్షి", em: "🐦" },
            { p: "ਮੱਛੀ", pr: "Machhi", en: "Fish", hi: "मछली", te: "చేప", em: "🐟" },
            { p: "ਅੱਖ", pr: "Akkh", en: "Eye", hi: "आँख", te: "కన్ను", em: "👁️" },
            { p: "ਕੰਨ", pr: "Kann", en: "Ear", hi: "कान", te: "చెవి", em: "👂" },
            { p: "ਨੱਕ", pr: "Nakk", en: "Nose", hi: "नाक", te: "ముక్కు", em: "👃" },
            { p: "ਹੱਥ", pr: "Hatth", en: "Hand", hi: "हाथ", te: "చెయ్యి", em: "✋" },
            { p: "ਪੈਰ", pr: "Pair", en: "Foot / Leg", hi: "पैर", te: "కాలు", em: "🦶" },
            { p: "ਸਿਰ", pr: "Sir", en: "Head", hi: "सिर", te: "తల", em: "👤" },
            { p: "ਦਿਲ", pr: "Dil", en: "Heart", hi: "दिल", te: "గుండె", em: "❤️" },
            { p: "ਸੂਰਜ", pr: "Sooraj", en: "Sun", hi: "सूरज", te: "సూర్యుడు", em: "☀️" },
            { p: "ਚੰਦ", pr: "Chand", en: "Moon", hi: "चाँद", te: "చంద్రుడు", em: "🌙" },
            { p: "ਅਸਮਾਨ", pr: "Asmaan", en: "Sky", hi: "आसमान", te: "ఆకాశం", em: "☁️" },
            { p: "ਮੀਂਹ", pr: "Meenh", en: "Rain", hi: "बारिश", te: "వర్షం", em: "🌧️" },
            { p: "ਹਵਾ", pr: "Hava", en: "Wind / Air", hi: "हवा", te: "గాలి", em: "💨" },
            { p: "ਅੱਗ", pr: "Agg", en: "Fire", hi: "आग", te: "నిప్పు", em: "🔥" },
            { p: "ਦਰਖਤ", pr: "Darakhat", en: "Tree", hi: "पेड़", te: "చెట్టు", em: "🌳" },
            { p: "ਇਹ ਕੀ ਹੈ?", pr: "Eh kee hai?", en: "What is this?", hi: "यह क्या है?", te: "ఇది ఏమిటి?", em: "❓" },
            { p: "ਇਹ ਕਿੱਥੇ ਹੈ?", pr: "Eh kitthe hai?", en: "Where is it?", hi: "यह कहाँ है?", te: "ఇది ఎక్కడ ఉంది?", em: "📍" },
            { p: "ਤੁਸੀਂ ਕੌਣ ਹੋ?", pr: "Tusi kaun ho?", en: "Who are you?", hi: "आप कौन हैं?", te: "మీరు ఎవరు?", em: "👤" },
            { p: "ਕਿਉਂ?", pr: "Kiyun?", en: "Why?", hi: "क्यों?", te: "ఎందుకు?", em: "🤔" },
            { p: "ਕਦੋਂ?", pr: "Kadon?", en: "When?", hi: "कब?", te: "ఎప్పుడు?", em: "🕒" },
            { p: "ਤੁਹਾਡਾ ਨਾਂ ਕੀ ਹੈ?", pr: "Tu-haa-da naa kee hai?", en: "What is your name?", hi: "आपका नाम क्या है?", te: "మీ పేరు ఏమిటి?", em: "📛" },
            { p: "ਮੇਰਾ ਨਾਂ ... ਹੈ", pr: "Me-ra naa ... hai", en: "My name is ...", hi: "मेरा नाम ... है", te: "నా పేరు ...", em: "👤" },
            { p: "ਕੀ ਹਾਲ ਹੈ?", pr: "Kee haal hai?", en: "How's it going? / How are you?", hi: "क्या हाल है?", te: "ఎలా ఉన్నారు?", em: "👋" },
            { p: "ਸਭ ਠੀਕ ਹੈ", pr: "Sabh theek hai", en: "Everything is fine", hi: "सब ठीक है", te: "అంతా బాగుంది", em: "👍" },
            { p: "ਫੇਰ ਮਿਲਾਂਗੇ", pr: "Pher mi-lan-ge", en: "See you again / See you later", hi: "फिर मिलेंगे", te: "మళ్ళీ కలుద్దాం", em: "👋" },
            { p: "ਕੋਈ ਗੱਲ ਨਹੀਂ", pr: "Ko-ee gall na-hi", en: "No problem / It's okay", hi: "कोई बात नहीं", te: "పర్వాలేదు", em: "😌" },
            { p: "ਵਾਹ ਬਈ ਵਾਹ!", pr: "Vaah bai vaah!", en: "Wow! / Excellent!", hi: "वाह भाई वाह!", te: "వావ్! అద్భుతం!", em: "🤩" },
            { p: "ਐਵੇਂ ਹੀ", pr: "Ai-vein hi", en: "Just like that / For no reason", hi: "ऐसे ही", te: "ఊరికే", em: "🤷" },
            { p: "ਮੈਨੂੰ ਨਹੀਂ ਪਤਾ", pr: "Mai-nu na-hi pa-ta", en: "I don't know", hi: "मुझे नहीं पता", te: "నాకు తెలియదు", em: "🤷‍♂️" },
            { p: "ਕੀ ਬਣਿਆ?", pr: "Kee ban-ya?", en: "What happened?", hi: "क्या हुआ?", te: "ఏమైంది?", em: "🧐" },
            { p: "ਮੈਨੂੰ ਭੁੱਖ ਲੱਗੀ ਹੈ", pr: "Mai-nu bhukh lag-gee hai", en: "I am hungry", hi: "मुझे भूख लगी है", te: "నాకు ఆకలిగా ఉంది", em: "😋" },
            { p: "ਤਿਆਰ ਹੋ ਜਾਓ", pr: "Tya-ar ho ja-o", en: "Get ready", hi: "तैयार हो जाओ", te: "తయారవ్వండి", em: "👟" },
            { p: "ਰੱਬ ਰਾਖਾ", pr: "Rabb raa-kha", en: "God be with you / Goodbye", hi: "भगवान भला करे", te: "దేవుడే రక్షకుడు", em: "🙌" },
            { p: "ਖੁਸ਼", pr: "Khush", en: "Happy", hi: "खुश", te: "సంతోషం", em: "😊" },
            { p: "ਉਦਾਸ", pr: "Udaas", en: "Sad", hi: "उदास", te: "బాధ", em: "😢" },
            { p: "ਵੱਡਾ", pr: "Vadda", en: "Big", hi: "बड़ा", te: "పెద్ద", em: "🐘" },
            { p: "ਛੋਟਾ", pr: "Chhota", en: "Small", hi: "छोटा", te: "చిన్న", em: "🐭" },
            { p: "ਗਰਮ", pr: "Garam", en: "Hot", hi: "गरम", te: "వేడి", em: "🔥" },
            { p: "ਠੰਢਾ", pr: "Thandhaa", en: "Cold", hi: "ठंडा", te: "చల్లని", em: "❄️" },
            { p: "ਚੰਗਾ", pr: "Changa", en: "Good", hi: "अच्छा", te: "మంచి", em: "👍" },
            { p: "ਬੁਰਾ", pr: "Bura", en: "Bad", hi: "बुरा", te: "చెడు", em: "👎" },
            { p: "ਸੋਹਣਾ", pr: "Sohna", en: "Beautiful / Handsome", hi: "सुंदर", te: "అందమైన", em: "✨" }
];
